### ISSUE TITLE
Graph input format

### ISSUE THREAD

**Issue by AstralisRL** [daiquocnguyen/Graph-Transformer#1]
Hello,

How should be the dataset.txt file storing the graph to be loaded correctly by load_data? I have a networkx graph dumped in json and would like to use your good work!

Thanks.

**Comment by daiquocnguyen** [comment]
Hi,

The text file data is formatted as follows: https://github.com/muhanzhang/pytorch_DGCNN/tree/master/data

* 1st line: `N` number of graphs; then the following `N` blocks describe the graphs  
* for each block of text:
  - a line contains `n l`, where `n` is number of nodes in the current graph, and `l` is the graph label
  - following `n` lines: 
    - the `i`th line describes the information of `i`th node (0 based), which starts with `t m`, where `t` is the tag of current node, and `m` is the number of neighbors of current node;
    - following `m` numbers indicate the neighbor indices (starting from 0). 
    - following `d` numbers (if any) indicate the continuous node features (attributes)

**Comment by WatsonWangZh** [comment]
> Hi,
> 
> The text file data is formatted as follows: https://github.com/muhanzhang/pytorch_DGCNN/tree/master/data
> 
> * 1st line: `N` number of graphs; then the following `N` blocks describe the graphs
> * for each block of text:
>   
>   * a line contains `n l`, where `n` is number of nodes in the current graph, and `l` is the graph label
>   * following `n` lines:
>     
>     * the `i`th line describes the information of `i`th node (0 based), which starts with `t m`, where `t` is the tag of current node, and `m` is the number of neighbors of current node;
>     * following `m` numbers indicate the neighbor indices (starting from 0).
>     * following `d` numbers (if any) indicate the continuous node features (attributes)

Is there an order requirement between nodes in the current graph?

**Comment by ScottLiao920** [comment]
hi, for DD dataset, as far as I know, the node tag can be one of 89 classes (downloaded from torch_geometric.dataset.TUDataset), however, in your dataset, it sits within 0~82, may I know the difference between yours and theirs?

**Comment by daiquocnguyen** [comment]
I use the same dataset taken from https://github.com/weihua916/powerful-gnns, which is the same as in  https://github.com/muhanzhang/pytorch_DGCNN. The statistic of the dataset is taken from the original paper: https://www.jmlr.org/papers/volume12/shervashidze11a/shervashidze11a.pdf

**Comment by ScottLiao920** [comment]
noted with thanks... I'll go figure out why there're 89 labels in TUDataset lol
Besides, I am working on a project that requires taking the gradient of input graph edge structure wrt model output, but currently, I believe the get_batch_data method is not differentiable... any suggestions on that?
