### ISSUE TITLE
No node attribute lables

### ISSUE THREAD

**Issue by JamesWBailey** [daiquocnguyen/Graph-Transformer#14]
Hi, thank you for research and your code, the results are excellent.

My issue is with datasets which usually have node attributes, not just node labels. For instance the original ENZYMES dataset includes 18 attributes per node, but the txt file in the zip lacks these attributes. I also haven't been able to find any reference to node attribute labels in the code, but I may be missing something obvious.

Is reading in node attribute labels a functionality you will eventually be able to add? Is it already implemented and I'm missing something? If it is impossible to add this functionality/ it will take a while to develop/ it's currently low priority because you think it'll have little impact on the results, would you mind clarifying that in the README?

Many thanks

**Comment by EdouardEPFL** [comment]
Did you manage to find how the conversion between the 18 attributes per node to a 0 or 1 node tag has been made ? I'm currently struggling to understand how to choose a strategy to label my nodes
