### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Deerzh** [daiquocnguyen/Graph-Transformer#16]
when I run this command:   $ python train_TextGNN.py --dataset mr --learning_rate 0.0001 --batch_size 4096 --num_epochs 150 --num_GNN_layers 2 --hidden_size 384 --model GatedGT,
an error occurred: 
Traceback (most recent call last):
  File "train_TextGNN.py", line 129, in <module>
    train_loss = train()
  File "train_TextGNN.py", line 99, in train
    torch.from_numpy(train_mask[idx]).float().to(device))
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhang/compatibility_analysis/Graph-Transformer/TextGNN/model_MPGNN.py", line 62, in forward
    graph_embeddings = torch.sum(x, 1) * torch.amax(x, 1)
AttributeError: module 'torch' has no attribute 'amax'
My torch version==1.5.0.
Can you help me solved this problem?

**Comment by daiquocnguyen** [comment]
I used PyTorch >= 1.5.0 when I reimplemented UGformer for graph classification. But after that, I used PyTorch >= 1.7.0 when I implemented UGformer for text classification. You can use PyTorch >= 1.7.0 to solve the problem.

**Comment by Deerzh** [comment]
Thank you for your reply, and I have run it successfully!
But now I have a new question. When I run this command:python train_UGformerV1_UnSup.py --dataset PTC --batch_size 2 --degree_as_tag --ff_hidden_size 1024 --num_neighbors 4 --num_sampled 512 --num_epochs 50 --num_timesteps 2 --learning_rate 0.0001 --model_name PTC_bs2_dro05_1024_4_idx0_2_2
an error occurred: 
ImportError: cannot import name 'LogUniformSampler' from 'log_uniform' (unknown location)

I found your previously reply in issues,
I run make in log_uniform directory,ang got information like this:
rm -rf build
rm -rf __pycache__
rm -rf log_uniform.cpp
rm -rf log_uniform.*.so 
python3 setup.py build_ext --inplace
Compiling log_uniform.pyx because it changed.
[1/1] Cythonizing log_uniform.pyx
/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/zhang/compatibility_analysis/Graph-Transformer/UGformerV1_PyTorch/log_uniform/log_uniform.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'log_uniform' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc -pthread -B /home/zhang/anaconda3/envs/Gra/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include -I/home/zhang/anaconda3/envs/Gra/include/python3.7m -c Log_Uniform_Sampler.cpp -o build/temp.linux-x86_64-3.7/Log_Uniform_Sampler.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/zhang/anaconda3/envs/Gra/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include -I/home/zhang/anaconda3/envs/Gra/include/python3.7m -c log_uniform.cpp -o build/temp.linux-x86_64-3.7/log_uniform.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
                 from /home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from log_uniform.cpp:807:
/home/zhang/anaconda3/envs/Gra/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-3.7
g++ -pthread -B /home/zhang/anaconda3/envs/Gra/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/zhang/anaconda3/envs/Gra/compiler_compat -L/home/zhang/anaconda3/envs/Gra/lib -Wl,-rpath=/home/zhang/anaconda3/envs/Gra/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/Log_Uniform_Sampler.o build/temp.linux-x86_64-3.7/log_uniform.o -o build/lib.linux-x86_64-3.7/log_uniform.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/log_uniform.cpython-37m-x86_64-linux-gnu.so ->

I don't know whether it make successfully.
And then I run this command:export PYTHONPATH="${PYTHONPATH}:~/compatibility_analysis/Graph-Transformer/UGformerV1_PyTorch/log_uniform"
Finally, it's failed too.
So,can you tell me which step I did wrong?

**Comment by daiquocnguyen** [comment]
You should use the absolute path for PYTHONPATH and then you can verify whether compiling log_uniform...so is successful by running UGformerV1_PyTorch/log_uniform/test.py

**Comment by Deerzh** [comment]
Thank you for your reply,I have solved that problem.
But now, an new error happend:
notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
usage: UGformer [-h] [--run_folder RUN_FOLDER] [--dataset DATASET]
                [--learning_rate LEARNING_RATE] [--batch_size BATCH_SIZE]
                [--num_epochs NUM_EPOCHS] [--model_name MODEL_NAME]
                [--sampled_num SAMPLED_NUM] [--dropout DROPOUT]
                [--num_hidden_layers NUM_HIDDEN_LAYERS]
                [--num_timesteps NUM_TIMESTEPS]
                [--ff_hidden_size FF_HIDDEN_SIZE]
                [--num_neighbors NUM_NEIGHBORS] [--fold_idx FOLD_IDX]
UGformer: error: unrecognized arguments: --degree_as_tag --num_sampled 512
I modify "--num_sampled" to "--sampled_num",
but I don't konw how to modify "--degree_as_tag"  
Can you tell me  how to do this?

**Comment by daiquocnguyen** [comment]
Thanks for pointing out this. The command you used is for TF version, not for PyTorch version. Please re-consider the updated README.

**Comment by Deerzh** [comment]
Thanks for your help！🤝
