### ISSUE TITLE
Issue while running the demo code

### ISSUE THREAD

**Issue by EdouardEPFL** [daiquocnguyen/Graph-Transformer#17]
Hello, I'm trying to run the Variant 1 demo with tensorflow: 
python train_UGformerV1_Sup.py --dataset IMDBBINARY --batch_size 4 --ff_hidden_size 1024 --fold_idx 1 --num_neighbors 8 --num_epochs 50 --num_timesteps 4 --learning_rate 0.0005 --model_name IMDBBINARY_bs4_fold1_1024_8_idx0_4_1

However I obtain the following error:

`Traceback (most recent call last):
  File "train_UGformerV1_Sup.py", line 11, in <module>
    from UGformerV1_Sup import UGformerV1
  File "/content/Graph-Transformer/UGformerV1_TF/UGformerV1_Sup.py", line 2, in <module>
    import universal_transformer_modified
  File "/content/Graph-Transformer/UGformerV1_TF/universal_transformer_modified.py", line 32, in <module>
    from tensor2tensor.models import transformer
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/models/__init__.py", line 51, in <module>
    from tensor2tensor.models.research import rl
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/models/research/rl.py", line 27, in <module>
    from tensor2tensor.envs import tic_tac_toe_env
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/envs/__init__.py", line 23, in <module>
    from tensor2tensor.envs import tic_tac_toe_env
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/envs/tic_tac_toe_env.py", line 244, in <module>
    register()
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/envs/tic_tac_toe_env.py", line 240, in register
    "tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv", version="v0")
  File "/usr/local/lib/python3.7/dist-packages/tensor2tensor/rl/gym_utils.py", line 360, in register_gym_env
    return env_name, gym.make(env_name)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 610, in make
    _kwargs = spec_.kwargs.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-8-114efe896dd4>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('bash', '', '#cd liblinear\n#cd U2GNN\ncd Graph-Transformer\ncd UGformerV1_TF\npython train_UGformerV1_Sup.py --dataset IMDBBINARY --batch_size 4 --ff_hidden_size 1024 --fold_idx 1 --num_neighbors 8 --num_epochs 50 --num_timesteps 4 --learning_rate 0.0005 --model_name IMDBBINARY_bs4_fold1_1024_8_idx0_4_1\n')

3 frames
[/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py](https://localhost:8080/#) in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

[/usr/local/lib/python3.7/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in named_script_magic(line, cell)
    140             else:
    141                 line = script
--> 142             return self.shebang(line, cell)
    143 
    144         # write a basic docstring:

<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py](https://localhost:8080/#) in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

[/usr/local/lib/python3.7/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'#cd liblinear\n#cd U2GNN\ncd Graph-Transformer\ncd UGformerV1_TF\npython train_UGformerV1_Sup.py --dataset IMDBBINARY --batch_size 4 --ff_hidden_size 1024 --fold_idx 1 --num_neighbors 8 --num_epochs 50 --num_timesteps 4 --learning_rate 0.0005 --model_name IMDBBINARY_bs4_fold1_1024_8_idx0_4_1\n'' returned non-zero exit status 1.`

I have all requirements up to date, do you have any idea how to fix it please ? I'm really interested in this repo

Thank you !

**Comment by EdouardEPFL** [comment]
Any idea please ?

**Comment by daiquocnguyen** [comment]
Hi, what do you mean by all requirements up to date? Did you try the code with Tensorflow 1.14, Tensor2tensor 1.13, Networkx 2.3, Scikit-learn 0.21.2?

**Comment by EdouardEPFL** [comment]
By up to date I meant the last versions.

I used : tensor2tensor 1.15.7
NetworkX 2.6.3
tensorflow 2.9.2
Scikit-learn 1.0.2

I'm going to try again with the version you suggested me.

**Comment by daiquocnguyen** [comment]
I implemented the UGformerV1 TF version around March 2019. Until now, there is a significance change from TF1 to TF2. That's why you could not run the code if you use TF2.

**Comment by EdouardEPFL** [comment]
Yes I managed to solve this problem using Torch, the problem come from TF2, it's only compatible with TF1. Anyways thank you for your help !
