### ISSUE TITLE
Build own dataset

### ISSUE THREAD

**Issue by HenriqueVarellaEhrenfried** [daiquocnguyen/Graph-Transformer#2]
@daiquocnguyen I enjoyed the work you created. I just wonder, how can I use it with my own dataset?  Could you please provide the pattern that the graphs should be?

**Comment by daiquocnguyen** [comment]
Hi,

The graph-structured data is formatted as follows: https://github.com/muhanzhang/pytorch_DGCNN/tree/master/data

* 1st line: `N` number of graphs; then the following `N` blocks describe the graphs  
* for each block of text:
  - a line contains `n l`, where `n` is number of nodes in the current graph, and `l` is the graph label
  - following `n` lines: 
    - the `i`th line describes the information of `i`th node (0 based), which starts with `t m`, where `t` is the tag of current node, and `m` is the number of neighbors of current node;
    - following `m` numbers indicate the neighbor indices (starting from 0). 
    - following `d` numbers (if any) indicate the continuous node features (attributes)
    
Hope this helps.

**Comment by HenriqueVarellaEhrenfried** [comment]
> Hi,
> 
> The graph-structured data is formatted as follows: https://github.com/muhanzhang/pytorch_DGCNN/tree/master/data
> 
> * 1st line: `N` number of graphs; then the following `N` blocks describe the graphs
> * for each block of text:
>   
>   * a line contains `n l`, where `n` is number of nodes in the current graph, and `l` is the graph label
>   * following `n` lines:
>     
>     * the `i`th line describes the information of `i`th node (0 based), which starts with `t m`, where `t` is the tag of current node, and `m` is the number of neighbors of current node;
>     * following `m` numbers indicate the neighbor indices (starting from 0).
>     * following `d` numbers (if any) indicate the continuous node features (attributes)
> 
> Hope this helps.

Thank you. In this format I have a couple of questions:

1) What is the tag `t`of a node?
2) Does U2GNN support the `d` numbers of node features?

**Comment by daiquocnguyen** [comment]
1. On bioinformatics datasets, `t` implies node labels as we use them to construct node feature vectors. On social network datasets, `t` is assigned to 0 to denote that nodes don't have available labels, thus node degrees are used to construct feature vectors.

2. Yes. U2GNN can support pre-defined node features, but with a slight modification in `util.py`:
- Change Line 83 by `g_list.append(S2VGraph(g, l, node_tags, node_features))`
- Comment # Lines 118-120

**Comment by ChenTao2017110** [comment]
How can I get the node labels?  How is t calculated? I can not understand what t means.

**Comment by HenriqueVarellaEhrenfried** [comment]
> How can I get the node labels? How is t calculated? I can not understand what t means.

I use the node labels as the class which the graph belongs.
