### ISSUE TITLE
Code run error

### ISSUE THREAD

**Issue by qycurious** [daiquocnguyen/Graph-Transformer#3]
Dear author, 
This error occurred when I was running the code in the process of reproducing your experimental results. Could you please give me a solution

`ValueError: The two structures don't have the same nested structure.

First structure: type=list str=[<tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/Identity:0' shape=() dtype=int32>, <tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/Identity_1:0' shape=(3, ?, 9, 65) dtype=float32>]

Second structure: type=list str=[<tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/add:0' shape=() dtype=int32>, (<tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/ffn/layer_postprocess/add:0' shape=(?, 9, 65) dtype=float32>, <tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/unstack:1' shape=(?, 9, 65) dtype=float32>, <tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/unstack:2' shape=(?, 9, 65) dtype=float32>)]

More specifically: Substructure "type=tuple str=(<tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/ffn/layer_postprocess/add:0' shape=(?, 9, 65) dtype=float32>, <tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/unstack:1' shape=(?, 9, 65) dtype=float32>, <tf.Tensor 'universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/unstack:2' shape=(?, 9, 65) dtype=float32>)" is a sequence, while substructure "type=Tensor str=Tensor("universal_transformer_encoder1/parallel_0_4/universal_transformer_encoder1/universal_transformer_encoder1/body/encoder/universal_transformer_basic/foldl/while/Identity_1:0", shape=(3, ?, 9, 65), dtype=float32)" is not`

**Comment by daiquocnguyen** [comment]
Do you have Python 3.6, Tensorflow 1.14 and Tensor2tensor 1.13, Networkx 2.3 and Scikit-learn 0.21.2?
