### ISSUE TITLE
Error while running "train_pytorch_U2GNN_UnSup.py"

### ISSUE THREAD

**Issue by sanjayagra** [daiquocnguyen/Graph-Transformer#8]
Hi, I am seeing the following error while running "train_pytorch_U2GNN_UnSup.py".
I see, this shows "cannot import name 'LogUniformSampler' from 'log_uniform' (unknown location)". But the file is already present in the mentioned path. I am not sure, why am I getting this error.
Please help me solving this issue.
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train_pytorch_U2GNN_UnSup.py", line 12, in <module>
    from pytorch_U2GNN_UnSup import *
  File "/mnt/c/Users/sanagraw/Documents/Graph/Graph-Transformer/U2GNN_pytorch/pytorch_U2GNN_UnSup.py", line 6, in <module>
    from sampled_softmax import  *
  File "/mnt/c/Users/sanagraw/Documents/Graph/Graph-Transformer/U2GNN_pytorch/sampled_softmax.py", line 7, in <module>
    from log_uniform import LogUniformSampler
ImportError: cannot import name 'LogUniformSampler' from 'log_uniform' (unknown location)
----------------------------------------------------------------------------------------------------

**Comment by daiquocnguyen** [comment]
You should change to the `log_uniform` directory to perform `make` to build `SampledSoftmax`, and then add the `log_uniform` directory to your PYTHONPATH.

**Comment by sanjayagra** [comment]
@daiquocnguyen can you please mention the steps if possible? I am not able to get it fully?

**Comment by daiquocnguyen** [comment]
If you are using bash, you use `cd` to go inside the `log_uniform` directory, then use `make` to compile the files. After that, you can use `export PYTHONPATH="${PYTHONPATH}:/path_to_log_uniform"` to add the `log_uniform` directory to your PYTHONPATH.

**Comment by miumiuUncle** [comment]
> 

how did you solve this problem? Please give a detailed answer。thanks

**Comment by Kryieee** [comment]
This really brings about a lot of difficulties for users to apply this model, wish a python version LogUniformSampler can be provided in this repo.
